import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { DashboardSidebar } from "@/components/dashboard/sidebar";
import { ThemeProvider } from "@/components/theme-provider"
import { NavigationProvider } from "@/components/navigation/navigation-provider";
import { PageRouter } from "@/components/navigation/page-router";
import Widget from "@/components/dashboard/widget";
import mockDataJson from "@/mock.json";
import type { MockData } from "@/types/dashboard";
import Notifications from "@/components/dashboard/notifications";

const mockData = mockDataJson as MockData

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TradeVault",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <NavigationProvider>
            <SidebarProvider>
              <div className="flex h-screen w-full">
                {/* Static Sidebar - Desktop */}
                <div className="hidden lg:flex flex-shrink-0">
                  <DashboardSidebar />
                </div>
                
                {/* Main Content Area - Scrollable */}
                <div className="flex-1 flex flex-col min-w-0">
                  <div className="flex-1 overflow-hidden">
                    <PageRouter />
                  </div>
                </div>
                
                <div className="hidden lg:flex flex-shrink-0 w-lg bg-sidebar border-l border-border">
                  <div className="w-full h-full flex flex-col p-4 space-y-4 overflow-hidden">
                    <div className="flex-shrink-0">
                      <Widget widgetData={mockData.widgetData} timezones={mockData.timezones || []} />
                    </div>
                    <div className="flex-1 min-h-0">
                      <Notifications
                        initialNotifications={mockData.notifications}
                      />
                    </div>
                  </div>
                </div>
              </div>
            </SidebarProvider>
          </NavigationProvider>
        </ThemeProvider>
        <div style={{ display: 'none' }}>{children}</div>
      </body>
    </html>
  );
}
